version: '3'
services:
    simulation:
        image: sitb157/rmf:humble 
        container_name: rmf
        privileged: true
        environment:
            #- "DISPLAY"
            #- "QT_X11_NO_MITSHM=1"
            #
            - DISPLAY=${IP}:0.0
        build:
            context: ./rmf_ws
            args: 
                - USER_NAME=${USER_NAME}
        user: ${USER_NAME}
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - $HOME/.Xauthority:/root/.Xauthority:rw
            - ./rmf_ws/src:/root/rmf_ws/src
        command: sleep infinity

