version: '3'
services:
    simulation:
        image: rmf_humble_simulation:latest
        container_name: rmf_humble_simulation
        privileged: true
        user: sitb157
        environment:
            - "DISPLAY"
            - "QT_X11_NO_MITSHM=1"
        build:
            context: ./simulation_ws
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - $HOME/.Xauthority:/root/.Xauthority:rw
            - ./simulation_ws/src:/root/simulation_ws/src
        command: sleep infinity

