version: '3'
services:
    robots:
      image: sitb157/ros-robots:humble 
      container_name: robots 
      privileged: true
      environment:
          #- "DISPLAY"
          #- "QT_X11_NO_MITSHM=1"
          - DISPLAY=${IP}:0.0
      network_mode: host
      build:
          context: ../robots_ws
          args: 
            - USER_NAME=${USER_NAME}
      user: ${USER_NAME}
      volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix:rw
          - $HOME/.Xauthority:/root/.Xauthority:rw
          - ../robots_ws/src:/root/robots_ws/src
      command: sleep infinity

    rmf:
      image: sitb157/ros-rmf:humble 
      container_name: rmf
      privileged: true
      environment:
          #- "DISPLAY"
          #- "QT_X11_NO_MITSHM=1"
          - DISPLAY=${IP}:0.0
      network_mode: host
      build:
          context: ../rmf_ws
          args: 
            - USER_NAME=${USER_NAME}
      user: ${USER_NAME}
      volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix:rw
          - $HOME/.Xauthority:/root/.Xauthority:rw
            #- ../rmf_ws/src:/root/rmf_ws/src
      command: sleep infinity

    navigation:
      image: sitb157/ros-navigation:humble 
      container_name: navigation 
      privileged: true
      environment:
          #- "DISPLAY"
          #- "QT_X11_NO_MITSHM=1"
          - DISPLAY=${IP}:0.0
      network_mode: host
      build:
          context: ../navigation_ws
          args: 
            - USER_NAME=${USER_NAME}
      user: ${USER_NAME}
      volumes:
          - /tmp/.X11-unix:/tmp/.X11-unix:rw
          - $HOME/.Xauthority:/root/.Xauthority:rw
          - ../navigation_ws/src:/root/navigation_ws/src
      command: sleep infinity

# For visulization with web
    novnc:  
      image: theasp/novnc:latest
      restart: always
      env_file:
        - novnc.env
      ports:
        - "9000:8080"
      networks:
         x11:
            ipv4_address: ${IP}
networks:
    x11:
       ipam:
          driver: default
          config:
              - subnet: "172.18.0.0/16"


