name: ROS BUILD

on:
  push:
    branches: [ "main", "devel" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['sitb157/rmf-simulation:humble']
    container:
      image: ${{ matrix.docker_image }}
    steps:
    #- name: create-ws
    #  run: |
    #    mkdir -p rmf_demos_ws/src
    - name: build
      shell: bash
      run: |
        cd simulation/
        source /opt/ros/humble/setup.bash
        export CXX=clang++
        export CX=clang
        colcon build --cmake-args -DNO_DOWNLOAD_MODELS=True
