name: ROS BUILD

on:
  push:
    branches: [ "main", "devel" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ['sitb157/rmf-simulation:humble']
    container:
      image: ${{ matrix.docker_image }}
    steps:   
    - name: ls -al
      run: |
        ls -al
    - uses: actions/checkout@v3
    - name: ls -al
      run: |
        ls -al
    - name: build
      shell: bash
      run: |
        cd build_ws
        source /opt/ros/humble/setup.bash
        export CXX=clang++
        export CX=clang
        colcon build --cmake-args -DNO_DOWNLOAD_MODELS=True
